[package]
name = "demodesktopgraphics"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
glutin = {git="https://github.com/rust-windowing/glutin.git"}
axgeom = "1.2"

[build-dependencies]
gl_generator = "0.13.0"


