[package]
name = "testy"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
build = "build.rs"


[dependencies]
glutin = {path="../glutin"}

[build-dependencies]
gl_generator = "0.5.0"


