[package]
name = "demodesktopgraphics"
version = "0.1.0"
authors = ["Ken Reed <kenakioreed@gmail.com>"]
build = "build.rs"
edition = "2018"

[dependencies]
glutin = "0.22.0-alpha3"
axgeom = "1.2.1"


[build-dependencies]
gl_generator = "0.13.0"


